#!/bin/bash
# create stable links for latest-BRANCH and specific supported Versions
set -u
wwwdir=/var/www/files/ffm
exitonerror=$1
ver=$2
branch=${3##*/}

DEPLOY_PATH="$(pwd)/${DEPLOY_PATH:-deploy-ffm}"
[[ $exitonerror -eq 1 ]] || shopt -s nullglob
[[ $exitonerror -eq 1 ]] && set -e

firmwares=( $DEPLOY_PATH/untested/*741* $DEPLOY_PATH/untested/*841* $DEPLOY_PATH/untested/*842* $DEPLOY_PATH/untested/*1043* $DEPLOY_PATH/untested/*wdr3600* $DEPLOY_PATH/untested/*wdr4300* )

cd ${wwwdir}

ln -sf ${branch}/$ver latest-${branch}

cd external/${branch}
for i in ${firmwares[@]}
do
  fname=${i##*/}

  if [[ ! -f "${i}" ]]
  then
  
    echo $fname not found - maybe the software does not fit into the flash of the device?
    if [[ $exitonerror -eq 1 ]]
    then 
      exit 1
    fi
  else
# images are not deployed yet - still create the links.
    type=factory
    if [[ $(echo $fname|grep -c factory) -eq 0 ]]
    then
      type=sysupgrade
    fi
    fpart=${fname%%$type*}
    rm -f ${fpart}latest-${branch}-$type.bin
    ln -s ../../${branch}/${ver}/firmware/${fname} ${fpart}latest-${branch}-$type.bin
  fi
done

