#!/bin/bash
# create stable links for latest-BRANCH and specific supported Versions
set -u
wwwdir=/var/www/files/ffm
exitonerror=$1
ver=$2
branch=${3##*/}

DEPLOY_PATH=${DEPLOY_PATH:-deploy-ffm}
[[ $exitonerror -eq 1 ]] || shopt -s nullglob
[[ $exitonerror -eq 1 ]] && set -e

firmwares=( $DEPLOY_PATH/untested/*741* $DEPLOY_PATH/untested/*841* $DEPLOY_PATH/untested/*842* $DEPLOY_PATH/untested/*1043* $DEPLOY_PATH/untested/*wdr3600* $DEPLOY_PATH/untested/*wdr4300* 

cd ${wwwdir}

ln -sf ${branch}/$ver latest-${branch}

cd external/${branch}
for i in ${firmwares[@]}
do
  fname=${i##*/}

  if [[ ! -f "../../${branch}/${ver}/firmware/${fname}" ]]
  then
  
    echo $fname not found
    [[ $exitonerror -eq 1 ]] && exit 1
  else
    type=factory
    [[ $(echo $fname|grep -c factory) -eq 0 ]] && type=sysupgrade
    fpart=${fname%%$type*}
    rm ${fpart}latest-${branch}-$type.bin
    ln -s ../../${branch}/${ver}/firmware/${fname} ${fpart}latest-${branch}-$type.bin
  fi
done

